##### Menu
menu:
  首页: /
  归档: /archives
  项目: /projects
  关于: /about
## you can create `tags` and `categories` folders in `../source`.
## And create a `index.md` file in each of them.
## set `front-matter`as
## layout: tags (or categories)
## title: tags (or categories)
## ---

#### Widgets
widgets: 
- category
- tag
- weibo
- rss
## provide seven widgets:category,tag,rss,archive,tagcloud,links,weibo
## modify links in `/layout/_widget/links.ejs`.

#### RSS 
rss: /atom.xml ## RSS address.

#### Image
imglogo:
  enable: true             ## display image logo true/false.
  src: img/logo.png        ## `.svg` and `.png` are recommended,please put image into the theme folder `/jacman/source/img`.
favicon: img/favicon.ico   ## size:32px*32px,`.ico` is recommended,please put image into the theme folder `/jacman/source/img`.     
apple_icon: img/icon.jpg  ## size:114px*114px,please put image into the theme folder `/jacman/source/img`.

#### Author Avatar Picture
author_img_enable: true ## display author avatar picture
dataURI: false
## if the picture's format is dataURI please set the value to true,otherwise set the value to false.
## convert an image into base 64 data URIs http://websemantics.co.uk/online_tools/image_to_data_uri_convertor/ .
author_img_data: 
## paste the dataURI in ONE LINE and included it by ''.
author_img: img/author.jpg ## size:220px*220px.
## if the picture's format is `.png` or `.jpg`  instead of dataURI,you should set the `dataURI` value to false.

#### Font
ShowCustomFont: true  
## you can change custom font in `variable.styl` and `font.styl` which in the theme folder `/jacman/source/css`.

#### Toc
toc:
  article: true   ## show contents in article.
  aside: true     ## show contents in aside.
## you can set both of the value to true of neither of them.
## if you don't want display contents in a specified post,you can modify `front-matter` and add `toc: false`.

#### Fancybox
fancybox: true 
## if you use gallery post or want use fancybox please set the value to true.
## if you want use fancybox in ANY post please copy the file `fancybox.js`.
## in theme folder `/jacman/scripts` to your hexo blog folder `../scritps`.

### Scroll to top
totop: false   ##show scroll-to-top in article
##if you want to scroll to top in every post set the value to true

#### Author information
author:
  intro_line1:  "Hello, I'm PhiloSky."  ## eg: "Hello ,I'm Larry Page in Google."
  intro_line2:  "This is my blog. Hope you enjoy it."  ## eg: "This is my blog,believe it or not."
  weibo:  5149155301    ## e.g. 5149155301 for http://weibo.com/5149155301
  twitter:  bluebird1314  ## e.g. bluebird1314 for https://twitter.com/bluebird1314
  github:  PhiloSky   ## e.g. PhiloSky for https://github.com/PhiloSky
  facebook:  tjuhanife ## e.g. wuchong for https://facebook.com/tjuhanife
  douban:  77474730   ## e.g. 77474730 or your id for https://www.douban.com/people/77474730
  tsina:  5149155301    ## e.g. 5149155301  Your weibo ID,It will be used in share button.
  email:  tjuhanife@gmail.com    ## e.g. tjuhanife@gmail.com
  google_plus:  115880271286802328613  ## eg:115880271286802328613 for https://plus.google.com/u/0/115880271286802328613
  stackoverflow: 3792490 ##3792490   ##e.g. 3222790 for http://stackoverflow.com/users/3792490/PhiloSky
## if you set them, the corresponding  share button will show on the footer
 

#### Comment
duoshuo: 
  enable: true  ## duoshuo.com
  short_name:  PhiloSky  ##e.g. PhiloSky   for duoshuo short name.

disqus:
  enable: false  ## disqus.com
  short_name:    ##e.g. wuchong   for disqus short name.  

#### Share button
jiathis:
  enable: false ## if you use jiathis as your share tool,the built-in share tool won't be display.
  id:    ## e.g. 1889330 your jiathis ID. 
  tsina: ## e.g. 2176287895 Your weibo id,It will be used in share button.

#### Custom Search
google_cse: 
  enable: true
  cx:  007881724004761432362:oso54v2u1lc ## e.g. 007881724004761432362:oso54v2u1lc your Custom Search ID.
## https://www.google.com/cse/ 
## To enable the custom search You must create a "search" folder in '/source' and a "index.md" file
## set the 'front-matter' as
## layout: search 
## title: search
## ---
  
  
#### Analytics
google_analytics:
  enable: false
  id:        ## e.g. UA-46321946-2 your google analytics ID.
  site:      ## e.g. wuchong.me your google analytics site or set the value as auto.
## You MUST upgrade to Universal Analytics first!
## https://developers.google.com/analytics/devguides/collection/upgrade/?hl=zh_CN

